- user:
    name: "git"
    comment: "Git User"
- name: "Add group for git"
  command: "/usr/sbin/usermod -a -G git {{ app_user_name }}"
- name: "chmod git home directory"
  become: yes
  file:
    path: "/home/git"
    mode: 0750
- name: "mkdir .ssh"
  become_user: git
  file:
    path: ".ssh"
    state: directory
    owner: git
    mode: 0700
## TODO: gitユーザー の ~/.ssh/authorized_keys にも、ec2への通常sshアクセスに使用しているのと同じ公開鍵をセット。
- name: "touch authorized_keys"
  become_user: git
  file:
    path: ".ssh/authorized_keys"
    state: touch
    owner: git
    mode: 0600
- name: copy publickey
  copy: src={{ public_key_file_name }} dest=/home/git/.ssh/authorized_keys

- name: "make git dir"
  become_user: git
  file:
    path: "deploy.git"
    state: directory
    owner: git
- name: "Init repository"
  become_user: git
  shell: >
    git init --bare;
  args:
    chdir: 'deploy.git'

- name: "make deploy directory"
  become_user: "{{ app_user_name }}"
  file:
    path: "{{ app_deploy_parent_path }}"
    state: directory
- name: "Init deploy directory"
  become_user: "{{ app_user_name }}"
  shell: >
    git clone /home/git/deploy.git deployed;
  args:
    chdir: "{{ app_deploy_parent_path }}"
  ignore_errors: True
