- name: install httpd
  yum: name=httpd

- name: "Add RVM to PATH"
  environment:
    PATH: "{{ ansible_env.PATH }}"
  shell: "source /etc/profile.d/rvm.sh"

- command: "which rvm"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
  register: rvm_installed
  ignore_errors: True

- name: "rvm use ruby-{{ ruby_version_25 }}"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
  command: "rvm use ruby-{{ ruby_version_25 }}"
  when: rvm_installed is success

- name: "Install passenger"
  environment:
    PATH: "{{ gem_27_path }}:{{ rvm_path }}:{{ ansible_env.PATH }}"
  command: "gem install passenger -v {{ passenger_version }} --no-ri --no-rdoc"
  when: rvm_installed is success

- name: "Install passenger apache2-module"
  environment:
    PATH: "{{ gem_27_path }}:{{ rvm_path }}:{{ ansible_env.PATH }}"
  command: "/usr/local/rvm/gems/ruby-{{ ruby_version_25 }}@global/gems/passenger-{{ passenger_version }}//bin/passenger-install-apache2-module --auto"
  when: rvm_installed is success

