- name: "Before install RVM"
  yum: name={{ item }} state=present
  with_items:
    - bison
    - libtool
    - sqlite-devel

#- name: "Prepare RVM"
#  command: "/usr/bin/gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
- name: "Download RVM Installer"
  # shell: '/usr/bin/curl -sSL https://get.rvm.io | bash -s stable --ruby >/dev/null 2>&1'
  get_url:
    url: https://get.rvm.io
    dest: '/tmp/rvm-installer.sh'
    mode: 0755
- name: "Install RVM"
  command: "/tmp/rvm-installer.sh"

- name: "Add RVM to PATH"
  shell: "source /etc/profile.d/rvm.sh"

- name: "Add group for RVM"
  command: "/usr/sbin/usermod -a -G rvm root"
#- name: "Add group for RVM"
#  command: "/usr/sbin/usermod -a -G rvm {{ admin_user_name }}"
- name: "Add group for RVM"
  command: "/usr/sbin/usermod -a -G rvm {{ app_user_name }}"

- name: "Install ruby-{{ ruby_version_25 }}"
  become: yes
  command: "/bin/bash -l -c \"rvm_rubygems_version={{ gem_version_27 }} /usr/local/rvm/bin/rvm reinstall ruby-{{ ruby_version_25 }} --disable-binary --with-gems=bundler,rake && /usr/local/rvm/bin/rvm --default ruby-{{ ruby_version_25 }}\""

- name: "put env file"
  become: yes
  template:
    src: env.j2
    dest: "/etc/profile.d/rvm_gems.sh"
- name: "make executable env file"
  become: yes
  file:
    path: "/etc/profile.d/rvm_gems.sh"
    mode: 0755

- name: "activate env"
  shell: bash -lc "/etc/profile.d/rvm_gems.sh"
